import 'package:doctorappointment/Services/sevice.dart';
import 'package:doctorappointment/modelClass.dart';
import 'package:flutter/material.dart';

class CustomCards extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    // TODO: implement createState
    //throw UnimplementedError();
    return CustomState();
  }
}

class CustomState extends State<CustomCards> {
  @override
  Widget build(BuildContext context) {
    final height = MediaQuery.of(context).size.height;
    final width = MediaQuery.of(context).size.width;
    Future<Autogenerated> futureUsers;
    // TODO: implement build
    // throw UnimplementedError();
    return Card(
      color: Colors.white,
      elevation: 10,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(50)),
      child: Column(
        // mainAxisAlignment: MainAxisAlignment.center,
        // crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Padding(
            padding: const EdgeInsets.only(top: 10, bottom: 10),
            child: Text(
              "hello",
              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
            ),
          ),
          Container(
            // color: Colors.yellowAccent,
            height: height * 0.48,
            child: FutureBuilder(
                future: fetchJSONData(),
                builder: (context, snapshot) {
                  if (!snapshot.hasData)
                    return Center(child: CircularProgressIndicator());
                  return ListView(
                    children: snapshot.data
                        .map<Widget>(
                          (user) => ListTile(
                            leading: Icon(
                              Icons.bookmark,
                              color: Colors.green,
                            ),
                            title: Text(user.name),
                            subtitle: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [Text(user.doctorName!=null?user.doctorName:'Default Value'), Text(user.name)],
                            ),
                            trailing: Column(
                              crossAxisAlignment: CrossAxisAlignment.end,
                              children: [
                                Text(user.name),
                                SizedBox(
                                  height: 8,
                                ),
                                Text('Dictation Pending'),
                              ],
                            ),
                          ),
                        )
                        .toList(),
                  );
                }),
          ),
        ],
      ),
    );
  }
}
